### PR TITLE
Add pangolin/pangoro runtime overrides files

### PR DESCRIPTION
**Pull request by boundless-forest**

### CODE REVIEW

**Comment by AurevoirXavier** [comment]
Why my generated WASM is different than yours.

**Comment by acgxv** [comment]
Why my generated WASM is different than yours.

**Comment by AurevoirXavier** [comment]
image

**Comment by acgxv** [comment]
image

**Comment by boundless-forest** [comment]
> Why my generated WASM is different than yours.

That's because the WASM files are generated on different platforms, Mac or Linux. We didn't use the srtool here.

**Comment by acgxv** [comment]
I'm on Linux too. I'd love to provide a smaller one.

**Comment by boundless-forest** [comment]
Both of them are okay for me as they are off-chain runtime files.

**Pull request merged**
